---
title: "Suppressing Black Votes: Replicating and Improving Figure 2"
author: "Byeolha Kim"
date: "2025-02-22"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(haven)
library(patchwork)
```

## Load Data

```{r load-data}
# Read in dataset
la_data <- read_dta("C:/Users/Byeolha Kim/OneDrive - american.edu/SIS-750-004/PS3-main/la_turnout_basic.dta")

# Clean understandingclause2 variable
la_data <- la_data %>%
  mutate(understandingclause2 = as.factor(understandingclause2),
         treated = ifelse(understandingclause2 == 1, "Treated", "Control")) %>%
  drop_na(blackregrate, whiteregrate) # Remove NA values
```

## Data Transformation

```{r transform-data}
# Summarizing data by year and treatment group
la_summary <- la_data %>%
  group_by(year, treated) %>%
  summarise(black_reg = mean(blackregrate, na.rm = TRUE),
            white_reg = mean(whiteregrate, na.rm = TRUE)) %>%
  pivot_longer(cols = c(black_reg, white_reg), names_to = "race", values_to = "registration_rate") %>%
  filter(year >= 1950 & year <= 1970) # Restrict year range
```

## Replicating Figure 2

```{r replicate-figure2}
p1 <- ggplot(filter(la_summary, race == "black_reg"), aes(x = year, y = registration_rate, color = treated, shape = treated)) +
  geom_line() +
  geom_point(size = 2, color = "black") +
  scale_shape_manual(values = c("Control" = 16, "Treated" = 17)) + # Circles for Control, Triangles for Treated
  scale_color_manual(values = c("Control" = "purple", "Treated" = "yellow")) + # Purple for Control, Yellow for Treated
  scale_x_continuous(breaks = seq(1950, 1970, 5)) + # Adjust year intervals
  scale_y_continuous(breaks = seq(0, 0.6, 0.2)) + # Adjust Y-axis breaks
  labs(y = "Black Registration Rate", x = "Year") +
  theme_minimal() +
  theme(plot.caption = element_text(hjust = 0.5)) +
  labs(caption = "(a) Black Registration")

p2 <- ggplot(filter(la_summary, race == "white_reg"), aes(x = year, y = registration_rate, color = treated, shape = treated)) +
  geom_line() +
  geom_point(size = 2, color = "black") +
  scale_shape_manual(values = c("Control" = 16, "Treated" = 17)) + # Circles for Control, Triangles for Treated
  scale_color_manual(values = c("Control" = "purple", "Treated" = "yellow")) + # Purple for Control, Yellow for Treated
  scale_x_continuous(breaks = seq(1950, 1970, 5)) + # Adjust year intervals
  scale_y_continuous(breaks = seq(0, 0.6, 0.2)) + # Adjust Y-axis breaks
  labs(y = "White Registration Rate", x = "Year") +
  theme_minimal() +
  theme(plot.caption = element_text(hjust = 0.5)) +
  labs(caption = "(b) White Registration")

# Combine with patchwork
p1 + p2
```

## Improved Figure 2

```{r improved-figure2}
# Define the Understanding Clause period
understanding_period <- data.frame(
  xmin = 1954, xmax = 1965, ymin = 0, ymax = 1
)

# Improved plot
improved_plot <- ggplot(la_summary, aes(x = year, y = registration_rate, color = treated, shape = treated)) +
  geom_rect(data = understanding_period, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
            inherit.aes = FALSE, fill = "gray", alpha = 0.2) +
  geom_line() +
  geom_point(size = 2, color = "black") +
  scale_shape_manual(values = c("Control" = 16, "Treated" = 17)) + # Circles for Control, Triangles for Treated
  scale_color_manual(values = c("Control" = "purple", "Treated" = "yellow")) + # Purple for Control, Yellow for Treated
  scale_x_continuous(breaks = seq(1950, 1970, 5)) + # Adjust year intervals
  scale_y_continuous(breaks = seq(0, 0.6, 0.2)) + # Adjust Y-axis breaks
  facet_wrap(~race, scales = "free_y", labeller = as_labeller(c(black_reg = "Black Registration", white_reg = "White Registration"))) +
  labs(y = "Registration Rate", x = "Year", title = "Improved Figure 2: Registration Rates by Race and Understanding Clause") +
  theme_minimal() +
  theme(panel.grid = element_blank(), strip.text = element_text(size = 12, face = "bold"),
        plot.caption = element_text(hjust = 0.5)) +
  labs(caption = "(a) Black Registration (left)  (b) White Registration (right)")

improved_plot
```

## Appendix

```{r appendix, echo=TRUE}
# Show full code for reproducibility
knitr::opts_chunk$set(echo = TRUE)
```
